package com.codeagent.context;

public enum InvalidationReason {
    INITIAL, PROVIDER_CHANGED, MODEL_CHANGED, CALL_CONFIG_CHANGED,
    TOOL_SCHEMA_CHANGED, COMPACTION, CLEAR, IMAGE_PAYLOAD_PRUNED,
    MESSAGE_REORDERED, MESSAGE_DELETED, UNSUPPORTED_CONTENT,
    USAGE_UNTRUSTED, OVERFLOW_RECOVERY
}
